### ISSUE TITLE
Issue opening the Program

### ISSUE THREAD

**Issue by MrRangerLP** [atom0s/Detox#12]
I tried to open the program after extracting it,

This is the crashlog:

!! CRASH !! Date: 15.06.2015 12:20:04
=================================================================================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at DetoxAPI.Extensions.AssemblyDefinitionExtensions.GetMethod(AssemblyDefinition asm, String parentType, String name, List`1 parameters)
   at Detox.Classes.DetoxInjections.LightingInjection(AssemblyDefinition asm)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Detox.Program.<Main>b__2(MethodInfo m)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Detox.Program.Main()

**Comment by Walkman100** [comment]
#10, #9, #8, #7, #6, #5...
@atom0s Maybe you should leave an open issue.

**Comment by atom0s** [comment]
Detox is currently no longer public accessible. However I may be reviving the project soon. (Granted it will not be free.)
